models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ~/app:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory ~/app --reload-on-changes ~/uc_app/uc_app/wsgi.py"
