models:
    image: tp33/django
    container_name: models
    external_links:
      -  mysql:db
    volumes:
      - ./uc_app:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations uc && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes uc_app/wsgi.py"
exp:
   image: tp33/django
   container_name: exp
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./exp_app:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes exp_app/wsgi.py"

web1:
   image: tp33/django
   container_name: web1
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./html_app:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes html_app/wsgi.py"

web2:
   image: tp33/django
   container_name: web2
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./html_app:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes html_app/wsgi.py"

haproxy:
  build: ./lb
  container_name: lb
  links:
    - web1:web1
    - web2:web2
  ports:
    - "80:8000"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch_1:
   image: tp33/django
   container_name: batch_1
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch_files_1:/app
   command: bash -c "python indexer.py"

batch_2:
  image: tp33/django
  container_name: batch_2
  links:
    - kafka:kafka
  volumes:
    - ./batch_files_2:/app
  command: bash -c "python item_views.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./batch_files_2/logs.txt:/tmp/data/logs.txt
    - ./batch_files_2/item_rec.py:/tmp/data/item_rec.py 

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./batch_files_2/logs.txt:/tmp/data/logs.txt
    - ./batch_files_2/item_rec.py:/tmp/data/item_rec.py

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web1:web1
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web1:web1
  volumes:
    - ./batch_files:/app
  command: bash -c "pip install selenium==3.0.1 && python /app/tester.py"
